<a href="https://colab.research.google.com/github/panzershracker/Data-analysis-algorithms/blob/master/HW_les_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
def calc_mse(y, y_pred):
  err = np.mean((y - y_pred)**2)
  return err

In [0]:
def calc_mae(y, y_pred):
  err = np.mean(np.abs(y - y_pred))
  return err

#**1. Подберите скорость обучения (alpha) и количество итераций:**

Используем некоторую погрешность "е", такую, что разница между предыдущей ошибкой и следующей, в пределах этой погрешности будет считаться достигнутым минимумом. Это позволит нам сократить кол-во итераций. Скорость обучения изменим с 1e-4 на 1e-2.

In [199]:
n = X.shape[1]
alpha = 0.01
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [200]:
%%time

e = 0.001
last_err = None


for i in range(1000):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  for j in range(len(W)):
    W[j] -= alpha * (1/n * 2 * np.sum(X[j] * (y_pred - y)))

  if last_err == None:
    last_err = err
    continue

  elif i % 50 == 0:
    print(i, W, err)

  elif last_err - err <= e:
    print(f'Вывод:\n Необходимое кол-во итераций = {i}\n Подобранные веса = {W}\n Финальная ошибка на данной итерации = {err}\n погрешность = {e}\n')
    break

  last_err = err

50 [21.35487986  8.68914872] 413.5487715072509
100 [31.88770806  6.74418155] 175.19445858001853
150 [38.13335681  5.59087473] 91.38594686849362
200 [41.83683774  4.90699865] 61.9177717428135
250 [44.03289    4.5014808] 51.556373747502974
300 [45.33508261  4.26102097] 47.913169919666785
350 [46.10724347  4.11843556] 46.63217153149881
400 [46.56511152  4.03388672] 46.181755648107604
450 [46.83661344  3.98375182] 46.023383498786444
Вывод:
 Необходимое кол-во итераций = 479
 Подобранные веса = [46.94003874  3.96465355]
 Финальная ошибка на данной итерации = 45.98434114415108
 погрешность = 0.001

CPU times: user 29.6 ms, sys: 939 µs, total: 30.5 ms
Wall time: 30.3 ms


#**!**
### Для первого задания хотел реализовать алгоритм имитации отжига с изменяющейся альфой для более быстрого нахождения минимума, но, не особо вышло.

#**2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:**

In [255]:
n = X.shape[1]
alpha = 0.01
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [256]:
X.shape, (W @ X).shape

((2, 10), (10,))

In [257]:
for i in range(1000):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  '''for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
  W -= (alpha * 1/n * 2 * ((y_pred - y) @ X.T))
  if i % 100 == 0:
    print(i, W, err)

0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.74418155] 175.19445858001853
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666785
400 [46.56511152  4.03388672] 46.181755648107604
500 [46.99760587  3.95402334] 45.96769776787538
600 [47.14967657  3.92594232] 45.941233404700036
700 [47.20314662  3.91606866] 45.93796156758051
800 [47.2219474   3.91259695] 45.93755706443538
900 [47.228558    3.91137626] 45.937507054979434


#**3. вместо того, чтобы задавать количество итераций, задайте условие остановки алгоритма - когда ошибка за итерацию начинает изменяться ниже определенного порога (упрощенный аналог параметра tol в линейной регрессии в sklearn).**

#**!**
Изначально я реализовал этот подход в первом задании, но повторим с примером из второго задания.

In [260]:
n = X.shape[1]
alpha = 0.01
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [261]:
%%time

e = 0.001
last_err = None

for i in range(1000):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  '''for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
  W -= (alpha * 1/n * 2 * ((y_pred - y) @ X.T))

  if last_err == None:
    last_err = err
    continue

  elif i % 100 == 0:
    print(i, W, err)
    
  elif last_err - err <= e:
    print(f'Вывод:\n Необходимое кол-во итераций = {i}\n Подобранные веса = {W}\n Финальная ошибка на данной итерации = {err}\n погрешность = {e}\n')
    break

  last_err = err

100 [31.88770806  6.74418155] 175.19445858001853
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666785
400 [46.56511152  4.03388672] 46.181755648107604
Вывод:
 Необходимое кол-во итераций = 479
 Подобранные веса = [46.94003874  3.96465355]
 Финальная ошибка на данной итерации = 45.98434114415108
 погрешность = 0.001

CPU times: user 25.6 ms, sys: 8.24 ms, total: 33.9 ms
Wall time: 30.8 ms
